###########
# site.url, site.title

title: 'Database Schema Documentation'
url:   'http://book-templates.github.io/schema'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false

